platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfperm/requirements
    tag: capi

run:
  path: perm-ci/tasks/test-ruby-client/task.sh
  args: []

inputs:
- name: perm-bin-dir
- name: perm-rb
- name: perm-ci
- name: version

params:
  PERM_TEST_SQL_DB_USERNAME: root
  PERM_TEST_SQL_DB_PASSWORD: password
  # ruby-mysql expects the socket to be at /tmp/mysql.sock
  # but this image puts it in /var/run/mysqld/mysqld.sock
  PERM_TEST_SQL_DB_SOCKET: /var/run/mysqld/mysqld.sock
  PERM_TEST_AUDIT_FILE_PATH: /var/log/perm-audit.log
