platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfperm/requirements
    tag: capi

run:
  path: perm-ci/tasks/test-ruby-client/task.sh
  args: []

inputs:
- name: perm-bin-dir
- name: perm-rb
- name: perm-ci

params:
  PERM_TEST_AUDIT_FILE_PATH: /var/log/perm-audit.log
