platform: linux

image_resource:
  type: docker-image
  source:
    repository: ruby
    tag: 2.4.2

run:
  path: perm-ci/tasks/test-ruby-client/task.sh
  args: []

inputs:
- name: perm-bin-dir
- name: perm-rb
- name: perm-ci
- name: version
