platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/capi
    tag: runtime-ci

inputs:
- name: branch-dir
- name: perm-ci
- name: release-dir
- name: version

outputs:
- name: release-output

params:
  RELEASE_NAME:

run:
  path: perm-ci/tasks/create-capi-pr-release/task.sh
