---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: concourse/bosh-cli

inputs:
- name: perm-ci
- name: version
- name: release-repo
- name: release-tarball

outputs:
- name: final-release-repo
- name: final-release-tarball

run:
  path: perm-ci/tasks/finalize-release/task.sh

params:
  BOSH_PRIVATE_CONFIG:
