---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: concourse/bosh-cli

inputs:
- name: perm-ci
- name: release
- name: version

outputs:
- name: release-output

run:
  path: perm-ci/tasks/create-release/task.sh

params:
  RELEASE_NAME:
  TARBALL_NAME:
