resources:
- name: perm-ci
  type: git
  source:
    uri: git@github.com/pivotal-cf/perm-ci
    branch: master
    private_key: ((github_bot_private_key))
- name: bosh-deployment
  type: git
  source:
    uri: git@github.com/cloudfoundry/bosh-deployment
    branch: master
    private_key: ((github_bot_private_key))
- name: ci-env-state
  type: git
  source:
    uri: git@github.com/pivotal-cf/perm-ci-credentials
    branch: master
    private_key: ((github_bot_private_key))
    paths:
    - gcp-account-creds.json
    - bbl-state.json
    - director-vars-store.yml
    - director-state.json
- name: director-ops-files
  type: git
  source:
    uri: git@github.com/pivotal-cf/perm-ci-credentials
    branch: master
    private_key: ((github_bot_private_key))
    paths:
    - director/*

jobs:
- name: deploy-director
  plan:
  - aggregate:
    - get: perm-ci
    - get: ci-env-state
    - get: bosh-deployment
    - get: director-ops-files
  - task: deploy-director
    file: perm-ci/tasks/create-env/task.sh
    input_mapping:
      perm-ci: perm-ci
      bosh-deployment: bosh-deployment
      state-dir: ci-env-state
      additional-ops-files-dir: director-ops-files/director
    output_mapping:
      updated-state-dir: updated-ci-env-state
    params:
      GCP_ZONE: ((gcp_zone))
      GCP_REGION: ((gcp_region))
      GCP_SERVICE_ACCOUNT_KEY_FILE: gcp-account-creds.json
      GCP_PROJECT_ID: ((gcp_project_id))
      ENV_NAME: ((director_name))
      VARS_STORE_FILE: director-vars-store.yml
      ENV_STATE_FILE: director-state.json
      BOSH_DEPLOYMENT_OPS_FILES: "gcp/cpi.yml uaa.yml credhub.yml external-ip-not-recommended.yml jumpbox-user.yml"
      ADDITIONAL_OPS_FILES: "director/credhub-mtls.yml"
      CRYPTDO_PASSWORD: ((cryptdo_password))
    ensure:
      put: ci-env-state
      params:
        repository: updated-ci-env-state
        rebase: true
