resource_types:
- name: bosh-deployment
  type: docker-image
  source:
    repository: cloudfoundry/bosh-deployment-resource
- name: gcs
  type: docker-image
  source:
    repository: frodenas/gcs-resource

resources:
- name: cf-deploy
  type: bosh-deployment
- name: cf-deployment
  type: git
  source:
    uri: git@github.com:cloudfoundry/cf-deployment.git
    private_key: ((github.private_key))
    branch: release-candidate
- name: perm-ci
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/perm-ci
    branch: master
    private_key: ((github.private_key))
- name: perm-ci-credentials
  type: git
  source:
    uri: git@github.com:pivotal-cf/perm-ci-credentials
    branch: master
    private_key: ((github.private_key))
- name: release-beta
  type: gcs
  source:
    bucket: perm-releases
    regexp: perm-release-(.*).tgz
    json_key: ((gcp.json_key))

jobs:
- name: deploy-cf
  plan:
  - aggregate:
    - get: cf-deployment
    - get: perm-ci
    - get: perm-ci-credentials
    - get: release-beta
  - do: &deploy-cf
    - do:
      - task: write-deployment-target-file
        file: perm-ci/tasks/write-deployment-target-file/task.yml
        params:
          CRYPTDO_PASSWORD: ((cryptdo_password))
          DEPLOYMENT_NAME: cf
          ENV_NAME: cleopatra
      - put: cf-deploy
        params:
          manifest: cf-deployment/cf-deployment.yml
          releases:
          - release-beta/*.tgz
          source_file: deployment-target-dir/target.yml
          ops_files:
          - cf-deployment/operations/experimental/enable-bpm.yml
          - cf-deployment/operations/experimental/skip-consul-cell-registrations.yml
          - cf-deployment/operations/experimental/skip-consul-locks.yml
          - cf-deployment/operations/experimental/use-bosh-dns.yml
          - cf-deployment/operations/experimental/disable-consul.yml
          - cf-deployment/operations/use-compiled-releases.yml
          - perm-ci/cf-deployment-operations/add-perm.yml
          - perm-ci/cf-deployment-operations/add-perm-monitor-api-sidecar.yml
          - perm-ci/cf-deployment-operations/add-cc-to-perm-migrator-errand.yml
          vars_files:
          - deployment-target-dir/vars.yml
