groups:
- name: develop
  jobs:
  - test-server
  - bump-submodule
  - bump-rc
  - create-release-rc

resource_types:
- name: gcs
  type: docker-image
  source:
    repository: frodenas/gcs-resource

resources:
- name: perm-ci
  type: git
  source:
    uri: git@github.com:pivotal-cf/perm-ci
    branch: master
    private_key: ((github.private_key))
- name: perm
  type: git
  source:
    uri: git@github.com:pivotal-cf/perm
    branch: master
    private_key: ((github.private_key))
- name: perm-release
  type: git
  source:
    uri: git@github.com:pivotal-cf/perm-release
    branch: master
    private_key: ((github.private_key))
- name: version
  type: semver
  source:
    driver: s3
    endpoint: storage.googleapis.com
    initial_version: 0.0.0
    bucket: perm-releases
    key: version
    access_key_id: ((gcp.access_key_id))
    secret_access_key: ((gcp.secret_access_key))
- name: release-rc
  type: gcs
  source:
    bucket: perm-release-candidates
    regexp: perm-(.*).tgz
    json_key: ((gcp.json_key))

jobs:
- name: test-server
  plan:
  - aggregate:
    - get: perm-ci
    - get: perm
      trigger: true
  - task: test-server
    file: perm-ci/tasks/test-server/task.yml

- name: bump-submodule
  plan:
  - aggregate:
    - get: perm-ci
    - get: perm-release
    - get: perm
      passed:
      - test-server
      trigger: true
  - task: bump-submodule
    file: perm-ci/tasks/bump-submodule/task.yml
    input_mapping:
      parent-repo: perm-release
      submodule-repo: perm
    output_mapping:
      updated-parent-repo: updated-perm-release
    params:
      SUBMODULE_PATH: src/code.cloudfoundry.org/perm
      SUBMODULE_NAME: perm
  - put: perm-release
    params:
      repository: updated-perm-release/parent-repo
      rebase: true

- name: bump-rc
  plan:
  - aggregate:
    - get: version
      params:
        pre: rc
    - get: perm
      passed:
      - bump-submodule
    - get: perm-release
      trigger: true
  - put: version
    params:
      file: version/version

- name: create-release-rc
  plan:
  - aggregate:
    - get: version
      passed:
      - bump-rc
      trigger: true
    - get: perm-release
      passed:
      - bump-rc
      trigger: true
    - get: perm-ci
  - task: create-release
    file: perm-ci/tasks/create-release/task.yml
    input_mapping:
      release: perm-release
    params:
      RELEASE_NAME: perm
  - put: release-rc
    params:
      file: release-output/perm-*.tgz
