resource_types:
- name: bosh-deployment
  type: docker-image
  source:
    repository: cloudfoundry/bosh-deployment-resource
- name: gcs
  type: docker-image
  source:
    repository: frodenas/gcs-resource
- name: git-branch-heads
  type: docker-image
  source:
    repository: vito/git-branch-heads-resource
- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource

resources:
- name: alpha
  type: semver
  source:
    driver: s3
    endpoint: storage.googleapis.com
    initial_version: 0.0.1
    bucket: perm-releases
    key: alpha-version
    access_key_id: ((gcp.access_key_id))
    secret_access_key: ((gcp.secret_access_key))
- name: beta
  type: semver
  source:
    driver: s3
    endpoint: storage.googleapis.com
    initial_version: 0.0.1
    bucket: perm-releases
    key: beta-version
    access_key_id: ((gcp.access_key_id))
    secret_access_key: ((gcp.secret_access_key))
- name: binary-alpha
  type: gcs
  source:
    bucket: perm-binaries
    regexp: perm-(\d+\.\d+\.\d+-alpha\.\d+).tgz
    json_key: ((gcp.json_key))
- name: binary-beta
  type: gcs
  source:
    bucket: perm-binaries
    regexp: perm-(\d+\.\d+\.\d+-beta\.\d+).tgz
    json_key: ((gcp.json_key))
- name: bosh-deployment
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry/bosh-deployment.git
    private_key: ((github.private_key))
- name: broken-pool-repo
  type: git
  source:
    branch: master
    uri: ((broken_pool_repo_uri))
    private_key: ((github.private_key))
- name: capi-ci
  type: git
  source:
    uri: git@github.com:cloudfoundry/capi-ci
    branch: master
    private_key: ((github.private_key))
- name: capi-release-alpha
  type: gcs
  source:
    bucket: perm-alphas
    regexp: capi-release-(\d+)-for-perm-.*.tgz
    json_key: ((gcp.json_key))
- name: capi-release-alpha-pr
  type: gcs
  source:
    bucket: perm-alphas
    regexp: capi-release-(\d+)-\w+-for-perm-.*.tgz
    json_key: ((gcp.json_key))
- name: capi-release-develop
  type: git
  source:
    uri: git@github.com:cloudfoundry/capi-release
    branch: develop
    private_key: ((github.private_key))
- name: cats-concourse-task
  type: git
  source:
    branch: master
    private_key: ((github.private_key))
    uri: git@github.com:cloudfoundry/cats-concourse-task.git
- name: cf-acceptance-tests
  type: git
  source:
    branch: master
    private_key: ((github.private_key))
    uri: git@github.com:cloudfoundry/cf-acceptance-tests.git
- name: cf-deploy
  type: bosh-deployment
- name: cf-deployment
  type: git
  source:
    uri: git@github.com:cloudfoundry/cf-deployment.git
    private_key: ((github.private_key))
    branch: release-candidate
- name: cloud_controller_ng-perm-prs
  type: git-branch-heads
  source:
    uri: git@github.com:cloudfoundry/cloud_controller_ng
    branches:
    - perm/*
    private_key: ((github.private_key))
- name: perm
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/perm
    branch: master
    private_key: ((github.private_key))
- name: perm-rb
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/perm-rb
    branch: master
    private_key: ((github.private_key))
- name: perm-ci
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/perm-ci
    branch: master
    private_key: ((github.private_key))
- name: perm-release
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/perm-release
    branch: master
    private_key: ((github.private_key))
- name: release-alpha
  type: gcs
  source:
    bucket: perm-alphas
    regexp: perm-release-(.*).tgz
    json_key: ((gcp.json_key))
- name: release-beta
  type: gcs
  source:
    bucket: perm-releases
    regexp: perm-release-(.*).tgz
    json_key: ((gcp.json_key))
- name: terraform
  type: terraform
  source:
    storage:
      endpoint: storage.googleapis.com
      bucket: ((terraform.bucket))
      bucket_path: bosh-lite/
      access_key_id: ((gcp.access_key_id))
      secret_access_key: ((gcp.secret_access_key))
- name: tracker
  type: tracker
  source:
    token: ((tracker.api_token))
    project_id: ((tracker.project_id))

jobs:
- name: test-server
  plan:
  - aggregate:
    - get: perm
      trigger: true
    - get: perm-ci
  - task: test-server
    file: perm-ci/tasks/test-server/task.yml

- name: bump-submodule
  plan:
  - aggregate:
    - get: perm
      passed:
      - test-server
      trigger: true
    - get: perm-ci
    - get: perm-release
  - task: bump-submodule
    file: perm-ci/tasks/bump-submodule/task.yml
    input_mapping:
      parent-repo: perm-release
      submodule-repo: perm
    output_mapping:
      updated-parent-repo: updated-perm-release
    params:
      SUBMODULE_PATH: src/code.cloudfoundry.org/perm
      SUBMODULE_NAME: perm
  - put: perm-release
    params:
      repository: updated-perm-release/parent-repo
      rebase: true

- name: bump-alpha
  plan:
  - aggregate:
    - get: perm
      passed:
      - bump-submodule
    - get: perm-release
      trigger: true
    - get: version
      resource: alpha
      params:
        pre: alpha
  - put: alpha
    params:
      file: version/version

- name: create-alpha
  plan:
  - aggregate:
    - get: perm
      passed:
      - bump-alpha
    - get: perm-ci
    - get: perm-release
      passed:
      - bump-alpha
    - get: version
      resource: alpha
      trigger: true
      passed:
      - bump-alpha
  - aggregate:
    - task: build-perm-binary
      file: perm-ci/tasks/build-binary/task.yml
      input_mapping:
        release: perm-release
      output_mapping:
        bin-dir: perm-bin-dir
      params:
        PACKAGE_PATH: code.cloudfoundry.org/perm/cmd/perm
        BINARY_NAME: perm
    - task: create-release
      file: perm-ci/tasks/create-release/task.yml
      input_mapping:
        release: perm-release
      params:
        RELEASE_NAME: perm
        TARBALL_NAME: perm-release
  - put: release-alpha
    params:
      file: release-output/perm-*.tgz
  - put: binary-alpha
    params:
      file: perm-bin-dir/perm-*.tgz

- name: test-ruby-client
  plan:
  - aggregate:
    - get: perm
      passed:
      - create-alpha
    - get: perm-bin-dir
      resource: binary-alpha
      passed:
      - create-alpha
    - get: perm-ci
    - get: perm-rb
      trigger: true
    - get: perm-release
      passed:
      - create-alpha
    - get: release-alpha
      passed:
      - create-alpha
    - get: version
      resource: alpha
      passed:
      - create-alpha
      trigger: true
  - task: test-ruby-client
    file: perm-ci/tasks/test-ruby-client/task.yml

- name: test-capi
  plan:
  - aggregate:
    - get: capi-ci
    - get: capi-release
      resource: capi-release-develop
      trigger: true
    - get: perm-bin-dir
      resource: binary-alpha
      passed:
      - create-alpha
    - get: perm-ci
    - get: release-alpha
      passed:
      - create-alpha
    - get: version
      resource: alpha
      passed:
      - create-alpha
      trigger: true
  - task: export-cloud_controller_ng
    file: perm-ci/tasks/export-subdirectory/task.yml
    input_mapping:
      parent: capi-release
    output_mapping:
      subdirectory: cloud_controller_ng
    params:
      SUBDIRECTORY_PATH: src/cloud_controller_ng
  - task: test-capi
    file: perm-ci/tasks/test-capi/task.yml

- name: test-capi-pr
  plan:
  - aggregate:
    - get: capi-ci
    - get: cloud_controller_ng
      resource: cloud_controller_ng-perm-prs
      trigger: true
      version: every
    - get: perm-bin-dir
      resource: binary-alpha
      passed:
      - create-alpha
    - get: perm-ci
    - get: release-alpha
      passed:
      - create-alpha
    - get: version
      resource: alpha
      passed:
      - create-alpha
  - task: test-capi
    file: perm-ci/tasks/test-capi/task.yml

- name: create-capi-alpha
  plan:
  - aggregate:
    - get: capi-release
      trigger: true
      resource: capi-release-develop
    - get: perm
      passed:
      - create-alpha
    - get: perm-ci
    - get: perm-release
      passed:
      - create-alpha
    - get: release-alpha
      passed:
      - create-alpha
    - get: version
      resource: alpha
      trigger: true
      passed:
      - create-alpha
  - task: create-capi-release
    file: perm-ci/tasks/create-capi-release/task.yml
    input_mapping:
      release: capi-release
    params:
      RELEASE_NAME: capi
  - put: capi-release-alpha
    params:
      file: release-output/capi-release-*.tgz

- name: create-capi-alpha-pr
  plan:
  - aggregate:
    - get: capi-release
      resource: capi-release-develop
    - get: cloud_controller_ng
      resource: cloud_controller_ng-perm-prs
      trigger: true
      version: every
    - get: perm
      passed:
      - create-alpha
    - get: perm-ci
    - get: perm-release
      passed:
      - create-alpha
    - get: release-alpha
      passed:
      - create-alpha
    - get: version
      resource: alpha
      passed:
      - create-alpha
  - aggregate:
    - task: bump-submodule
      file: perm-ci/tasks/bump-submodule/task.yml
      input_mapping:
        parent-repo: capi-release
        submodule-repo: cloud_controller_ng
      output_mapping:
        updated-parent-repo: updated-capi-release-dir
      params:
        SUBMODULE_PATH: src/cloud_controller_ng
        SUBMODULE_NAME: cloud_controller_ng
    - task: get-branch-name
      file: perm-ci/tasks/get-branch-name/task.yml
      input_mapping:
        repo: cloud_controller_ng
  - task: create-capi-pr-release
    file: perm-ci/tasks/create-capi-pr-release/task.yml
    input_mapping:
      release-dir: updated-capi-release-dir
    params:
      RELEASE_NAME: capi
  - put: capi-release-alpha-pr
    params:
      file: release-output/capi-release-*.tgz

- name: deploy-cf
  plan:
  - aggregate:
    - get: bosh-deployment
    - get: broken-pool-repo
    - get: capi-ci
    - get: capi-release-alpha
      trigger: true
      passed:
      - create-capi-alpha
    - get: capi-release
      resource: capi-release-develop
      passed:
      - create-capi-alpha
    - get: cf-deployment
    - get: perm
      passed:
      - create-capi-alpha
    - get: perm-ci
    - get: perm-release
      passed:
      - create-capi-alpha
    - get: release-alpha
      trigger: true
      passed:
      - create-capi-alpha
    - get: version
      resource: alpha
      trigger: true
      passed:
      - create-capi-alpha
  - do: &deploy-cf
    - put: terraform
      params:
        delete_on_failure: true
        generate_random_name: true
        terraform_source: capi-ci/terraform/bosh-lite
        vars: &test_cf_terraform_vars
          dns_json_key: ((gcp.json_key))
          dns_project_id: ((gcp.project_id))
          dns_zone_name: ((terraform.dns_zone_name))
          json_key: ((gcp.json_key))
          project_id: ((gcp.project_id))
          region: ((gcp.region))
          system_domain_suffix: ((terraform.system_domain_suffix))
          zone: ((gcp.zone))
    - do:
      - task: create-bosh-lite
        file: capi-ci/ci/bosh-lite/create-bosh-lite.yml
        params:
          GCP_JSON_KEY: ((gcp.json_key))
        on_failure:
          put: terraform
          get_params:
            action: destroy
          params:
            action: destroy
            env_name_file: terraform/name
            terraform_source: capi-ci/terraform/bosh-lite
            vars: *test_cf_terraform_vars
      - do:
        - task: create-env-vars-file
          file: capi-ci/ci/bosh-lite/create-env-vars-file.yml
        - task: upload-cf-assets
          file: capi-ci/ci/bosh-lite/upload-cf-assets.yml
        - task: write-bosh-target-file
          file: capi-ci/ci/bosh-lite/write-bosh-target-file.yml
        - task: upload-to-gcs
          file: capi-ci/ci/gcs/upload-to-gcs.yml
          input_mapping:
            environment: terraform
            source-directory: director-state
          params: &gcp-environment-params
            GCP_JSON_KEY: ((gcp.json_key))
            GCP_BUCKET: ((terraform.bucket))
            GCP_PATH: director-state
            USE_ENV_NAMED_SUBDIR: true
        on_failure: &cf-deploy-failure
          do:
          - task: delete-bosh-lite
            file: capi-ci/ci/bosh-lite/delete-bosh-lite.yml
          - put: terraform
            params:
              action: destroy
              env_name_file: terraform/name
              terraform_source: capi-ci/terraform/bosh-lite
              vars: *test_cf_terraform_vars
            get_params:
              action: destroy
      - put: cf-deploy
        params:
          source_file: bosh-target/target.yml
          manifest: cf-deployment/cf-deployment.yml
          releases:
          - release-alpha/*.tgz
          - capi-release-alpha/*.tgz
          vars_files:
          - bosh-target/vars.yml
          ops_files:
          - perm-ci/cf-deployment-operations/undo-metron-addon.yml
          - capi-ci/cf-deployment-operations/skip-cert-verify.yml
          - capi-ci/cf-deployment-operations/use-latest-stemcell.yml
          - cf-deployment/operations/bosh-lite.yml
          - cf-deployment/operations/use-compiled-releases.yml
          - perm-ci/cf-deployment-operations/add-bpm.yml
          - perm-ci/cf-deployment-operations/add-perm.yml
          - perm-ci/cf-deployment-operations/add-perm-monitor-api-sidecar.yml
          - capi-ci/cf-deployment-operations/use-latest-capi.yml
        on_failure:
          do:
          - task: pend-broken-environment
            file: perm-ci/tasks/pend-broken-environment/task.yml
            params:
              POOL_NAME: bosh-lites-broken
            input_mapping:
              environment-name-dir: terraform
              pool-repo: broken-pool-repo
          - put: broken-pool-repo
            params:
              repository: updated-pool-repo-dir/repo
              rebase: true
          on_failure: *cf-deploy-failure

- name: deploy-cf-pr
  plan:
  - aggregate:
    - get: bosh-deployment
    - get: broken-pool-repo
    - get: capi-ci
    - get: capi-release
      resource: capi-release-develop
      passed:
      - create-capi-alpha-pr
    - get: capi-release-alpha
      resource: capi-release-alpha-pr
      trigger: true
      passed:
      - create-capi-alpha-pr
    - get: cf-deployment
    - get: cloud_controller_ng
      resource: cloud_controller_ng-perm-prs
      passed:
      - create-capi-alpha-pr
    - get: perm
      passed:
      - create-capi-alpha-pr
    - get: perm-ci
    - get: perm-release
      passed:
      - create-capi-alpha-pr
    - get: release-alpha
      passed:
      - create-capi-alpha-pr
    - get: version
      resource: alpha
      passed:
      - create-capi-alpha-pr
  - do: *deploy-cf

- name: test-cf
  plan:
  - aggregate:
    - get: broken-pool-repo
    - get: capi-ci
    - get: capi-release
      resource: capi-release-develop
      passed:
      - deploy-cf
    - get: capi-release-alpha
      trigger: true
      passed:
      - deploy-cf
    - get: cats-concourse-task
    - get: cf-acceptance-tests
    - get: perm
      passed:
      - deploy-cf
    - get: perm-ci
    - get: perm-release
      trigger: true
      passed:
      - deploy-cf
    - get: release-alpha
      passed:
      - deploy-cf
    - get: terraform
      trigger: true
      passed:
      - deploy-cf
      trigger: true
    - get: version
      resource: alpha
      passed:
      - deploy-cf
  - do: &test-cf
    - task: download-from-gcs
      file: capi-ci/ci/gcs/download-from-gcs.yml
      input_mapping:
        environment: terraform
      output_mapping:
        destination-directory: environment-directory
      params: *gcp-environment-params
    - task: write-cats-config
      file: perm-ci/tasks/write-cats-config/task.yml
      output_mapping:
        cats-config-dir: integration-config
    - task: run-cats
      file: cats-concourse-task/task.yml
      params:
        NODES: 8
      ensure:
        do:
        - task: pend-broken-environment
          file: perm-ci/tasks/pend-broken-environment/task.yml
          params:
            POOL_NAME: bosh-lites-broken
          input_mapping:
            environment-name-dir: terraform
            pool-repo: broken-pool-repo
        - put: broken-pool-repo
          params:
            repository: updated-pool-repo-dir/repo
            rebase: true

- name: test-cf-pr
  plan:
  - aggregate:
    - get: broken-pool-repo
    - get: capi-ci
    - get: capi-release
      resource: capi-release-develop
      passed:
      - deploy-cf-pr
    - get: capi-release-alpha-pr
      trigger: true
      passed:
      - deploy-cf-pr
    - get: cats-concourse-task
    - get: cf-acceptance-tests
    - get: cloud_controller_ng
      resource: cloud_controller_ng-perm-prs
      passed:
      - deploy-cf-pr
    - get: perm
      passed:
      - deploy-cf-pr
    - get: perm-ci
    - get: perm-release
      passed:
      - deploy-cf-pr
    - get: release-alpha
      passed:
      - deploy-cf-pr
    - get: terraform
      passed:
      - deploy-cf-pr
      trigger: true
    - get: version
      resource: alpha
      passed:
      - deploy-cf-pr
  - do: *test-cf

- name: bump-beta
  plan:
  - aggregate:
    - get: beta
      params:
        pre: beta
    - get: capi-release
      resource: capi-release-develop
      passed:
      - test-cf
    - get: perm
      passed:
      - test-cf
    - get: perm-release
      passed:
      - test-cf
    - get: version
      resource: alpha
      trigger: true
      passed:
      - test-cf
  - put: beta
    params:
      file: beta/version

- name: create-beta
  plan:
  - aggregate:
    - get: alpha
      passed:
      - bump-beta
    - get: capi-release
      resource: capi-release-develop
      passed:
      - bump-beta
    - get: perm
      passed:
      - bump-beta
    - get: perm-ci
    - get: perm-release
      passed:
      - bump-beta
    - get: version
      resource: beta
      trigger: true
      passed:
      - bump-beta
  - aggregate:
    - task: build-perm-binary
      file: perm-ci/tasks/build-binary/task.yml
      input_mapping:
        release: perm-release
      output_mapping:
        bin-dir: perm-bin-dir
      params:
        PACKAGE_PATH: code.cloudfoundry.org/perm/cmd/perm
        BINARY_NAME: perm
    - task: create-release
      file: perm-ci/tasks/create-release/task.yml
      input_mapping:
        release: perm-release
      params:
        RELEASE_NAME: perm
        TARBALL_NAME: perm-release
  - put: release-beta
    params:
      file: release-output/perm-*.tgz
  - put: binary-beta
    params:
      file: perm-bin-dir/perm-*.tgz

- name: deliver-stories
  plan:
  - aggregate:
    - get: capi-release
      resource: capi-release-develop
      passed:
      - test-cf
      - test-capi
    - get: perm
      passed:
      - test-cf
    - get: perm-ci
    - get: perm-rb
      passed:
      - test-ruby-client
    - get: perm-release
      passed:
      - test-cf
    - get: release-alpha
      passed:
      - test-cf
    - get: version
      resource: alpha
      trigger: true
      passed:
      - test-cf
  - put: tracker
    params:
      repos:
      - capi-release
      - perm-release/src/cloud_controller_ng
      - perm
      - perm-rb
      - perm-release
