groups:
- name: develop
  jobs:
  - test-server
  - test-release
  - rc
  - build-release-rc

resources:
- name: perm-ci
  type: git
  source:
    uri: git@github.com/pivotal-cf/perm-ci
    branch: master
    private_key: {{github_bot_private_key}}
- name: perm-repo
  type: git
  source:
    uri: git@github.com/pivotal-cf/perm-release
    branch: master
    private_key: {{github_bot_private_key}}
- name: perm-server
  type: git
  source:
    uri: git@github.com/pivotal-cf/perm-release
    branch: master
    private_key: {{github_bot_private_key}}
    paths:
    - src/**/*
- name: perm-release
  type: git
  source:
    uri: git@github.com/pivotal-cf/perm-release
    branch: master
    private_key: {{github_bot_private_key}}
    ignore_paths:
    - src/**/*
- name: version
  type: semver
  source:
    bucket: perm-releases
    key: current-version
    access_key_id: {{perm_releases_bucket_access_key}}
    secret_access_key: {{perm_releases_bucket_secret_key}}

jobs:
- name: test-server
  plan:
  - aggregate:
    - get: perm-ci
    - get: perm-server
      trigger: true
    - get: perm-repo
  - task: test-server
    file: perm-ci/tasks/test-server/task.yml

- name: test-release
  plan:
  - aggregate:
    - get: perm-ci
    - get: perm-release
      trigger: true
    - get: perm-repo
  - task: test-release
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: alpine
        run:
          path: echo
          args: "This is a placeholder"

- name: rc
  plan:
  - aggregate:
    - get: version
      params:
        pre: rc
    - get: perm-server
      passed:
      - test-server
      trigger: true
    - get: perm-release
      passed:
      - test-release
      trigger: true
    - get: perm-repo
      passed:
      - test-server
      - test-release
  - put: version
    params:
      file: version/version

- name: build-release-rc
  plan:
  - aggregate:
    - get: version
    - get: perm-ci
    - get: perm-repo
      passed:
      - rc
      trigger: true
  - task: create-release
    file: perm-ci/tasks/create-release/task.yml
    input_mapping:
      release: perm-repo
  - put: release-rc
    params:
      file: release-output/perm-*.tgz
