platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: alpine3.6

inputs:
- name: release
- name: perm-ci
- name: version

outputs:
- name: bin-dir

run:
  path: perm-ci/tasks/build-binary/task.sh
  args: []

params:
  GOARCH: amd64
  GOOS: linux
  CGO_ENABLED: 0
  PACKAGE_PATH:
  BINARY_NAME:
