platform: linux

image_resource:
  type: docker-image
  source:
    repository: concourse/buildroot
    tag: git

inputs:
- name: perm-ci
- name: repo

run:
  path: perm-ci/tasks/get-branch-name/task.sh
