platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfperm/requirements
    tag: capi

inputs:
- name: perm-ci
- name: capi-ci
- name: perm-bin-dir
- name: cloud_controller_ng
- name: version

run:
  path: perm-ci/tasks/test-capi/task.sh

params:
  TEST_MYSQL_USERNAME: root
  TEST_MYSQL_PASSWORD: password
  # ruby-mysql expects the socket to be at /tmp/mysql.sock
  # but this image puts it in /var/run/mysqld/mysqld.sock
  PERM_TEST_SQL_DB_SOCKET: /var/run/mysqld/mysqld.sock
