platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/capi
    tag: ruby-units

inputs:
- name: perm-ci
- name: capi-ci
- name: perm-bin-dir
- name: cloud_controller_ng
- name: version

run:
  path: perm-ci/tasks/test-capi/task.sh
