platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfseceng/credhub

inputs:
- name: environment-directory
- name: perm-ci
- name: terraform

run:
  path: perm-ci/tasks/run-bosh-errand/task.sh

params:
  BOSH_DEPLOYMENT:
  BOSH_ERRAND_NAME:
  BOSH_CLIENT: admin
