---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfperm/requirements
    tag: base

inputs:
- name: perm-ci
- name: perm-release

run:
  path: perm-ci/tasks/test-migrator/task.sh
