platform: linux

image_resource:
  type: docker-image
  source:
    repository: concourse/buildroot
    tag: git

inputs:
- name: perm-ci
- name: parent-repo
- name: submodule-repo

outputs:
- name: updated-parent-repo

params:
  SUBMODULE_PATH:
  SUBMODULE_NAME:

run:
  path: perm-ci/tasks/bump-submodule/task.sh
